<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CheckCritical" Id="{b7f02efc-5073-4782-bdb4-49dadea447fc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CheckCritical : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//CheckCritical

CheckCritical := 
    NOT GVL_FSM.bsdc_closed OR
    GVL_PT.ERROR_STATUS <> 0 OR
    GVL_PT.MAX_TEMP > GVL_FSM.rcritical_temp_PT OR 
	GVL_THERMAL.bEMSOVERHEAT OR 
	GVL_THERMAL.bFLOWOVERHEAT OR 
	GVL_THERMAL.bHEMSOVERHEAT OR 
	GVL_THERMAL.bMOTOROVERHEAT OR
    GVL_LEVI.levitation_fault OR
    GVL_Prop.propulsion_fault;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>