<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Charge" Id="{28101247-21c0-4e15-930b-d770b5ff78d6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Charge
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Send command to PT to trigger precharge ]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>