<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Discharge" Id="{9b334204-e1f0-4f77-8568-487de87d10d1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Discharge
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Send command to PT to trigger DIscharge]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>