<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Handle_Movement" Id="{b6b3d548-c2a6-4783-8489-7feef4129cea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Handle_Movement : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//direct pull to emetgency checks here?]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>