<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SC_MAIN_FSM" Id="{8ae7d21a-5b8b-4fb0-8d34-ff7e9a16183c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SC_MAIN_FSM
VAR
	main_fsm	: FB_Main_FSM;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[main_fsm(currentCmd := GVL_FSM.E_CommandGlobal, EmergencyReason := GVL_FSM.EmergencyReason);

// GVL_FSM.fbLink();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>